services:
  db:
    image: postgres:16-alpine
    container_name: exam_db
    environment:
      POSTGRES_USER: exam
      POSTGRES_PASSWORD: exam
      POSTGRES_DB: examdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U exam -d examdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: exam_api

    # 🔴 READ ENV FILE
    env_file:
      - .env

    # 🔴 FORCE ENV INTO CONTAINER
    environment:
      NODE_ENV: development

      # Database
      DATABASE_URL: ${DATABASE_URL}

      # Uploads
      UPLOAD_DIR: ${UPLOAD_DIR}

      # AI Settings
      AI_MODEL: ${AI_MODEL}
      GEMINI_API_KEY: ${GEMINI_API_KEY}

      # App
      PORT: 4000
      JWT_SECRET: ${JWT_SECRET}

    ports:
      - "4000:4000"

    volumes:
      - .:/app


    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
